<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::create(['nama' => 'Alif Zakiansyah As Syauqi', 'jenis_kelamin' => 'Pria', 'himada' => 'Kemass']);
        User::create(['nama' => 'Dimas Gifari', 'jenis_kelamin' => 'Pria', 'himada' => 'Kemass']);
        User::create(['nama' => 'Dio Tegar Pangestu', 'jenis_kelamin' => 'Pria', 'himada' => 'Kemass']);
        User::create(['nama' => 'Dita Windy Amanda', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kemass']);
        User::create(['nama' => 'Ghevira Faradilla', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kemass']);
        User::create(['nama' => 'Hawa Kurnia', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kemass']);
        User::create(['nama' => 'Imam Addarul Quthni', 'jenis_kelamin' => 'Pria', 'himada' => 'Kemass']);
        User::create(['nama' => 'Lola Monica', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kemass']);
        User::create(['nama' => 'M. Arkillah Ibnu Asshiddiqie', 'jenis_kelamin' => 'Pria', 'himada' => 'Kemass']);
        User::create(['nama' => 'M. Davindra Alfariz Silaen', 'jenis_kelamin' => 'Pria', 'himada' => 'Kemass']);
        User::create(['nama' => 'M. Fadhil Fayyad', 'jenis_kelamin' => 'Pria', 'himada' => 'Kemass']);
        User::create(['nama' => 'M. Febriansyah', 'jenis_kelamin' => 'Pria', 'himada' => 'Kemass']);
        User::create(['nama' => 'Maharani', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kemass']);
        User::create(['nama' => 'Misbahul Jannah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kemass']);
        User::create(['nama' => 'Muhammad Aflah Diandra', 'jenis_kelamin' => 'Pria', 'himada' => 'Kemass']);
        User::create(['nama' => 'Muhammad Gusti Nur Aditya', 'jenis_kelamin' => 'Pria', 'himada' => 'Kemass']);
        User::create(['nama' => 'Muhammad Ihsan', 'jenis_kelamin' => 'Pria', 'himada' => 'Kemass']);
        User::create(['nama' => 'Muhammad Putra Anggoro', 'jenis_kelamin' => 'Pria', 'himada' => 'Kemass']);
        User::create(['nama' => 'Muhammad Raza Anugrah', 'jenis_kelamin' => 'Pria', 'himada' => 'Kemass']);
        User::create(['nama' => 'Muhammad Surya Nugraha Saputra', 'jenis_kelamin' => 'Pria', 'himada' => 'Kemass']);
        User::create(['nama' => 'Naila Kezha Putri', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kemass']);
        User::create(['nama' => 'Nuzul Athaillah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kemass']);
        User::create(['nama' => 'Rizki Allysa Ibrahim Putri', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kemass']);
        User::create(['nama' => 'Siti Afifah Putri Santosa', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kemass']);
        User::create(['nama' => 'Siti Fatimah Azzahra', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kemass']);
        User::create(['nama' => 'Tarysa Nabila Putri Zuci', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kemass']);
        User::create(['nama' => 'Arif Budiman', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Asjad Lathifah Lama\'a', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Aprilia Kartika', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Lili Nurindahsari', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Mohamad Aldi Amirul Rasyid', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Nadira Rahma Prameswari', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Ratika Jihan Khairunnisa', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Tivanny Rahma Safura', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Viola Hanif Trimaharani', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Aldila Salwa Salsabila', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Elang Permana', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Hanifah Luthfiannisa', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Mutia Lu\'lu Alhawa', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Nitis Sukma Wulan Ayu', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Salsabila Zulfa Putriliana', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Viranosa Ariana Hafsari', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Alfina Azizah Zalmani', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Farel Fajar Prasetyo', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Indah Wahyuning Utami', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Nadia Zulfaa', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Olivia Mirza Andriani', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Sukma Amalia Sabrina', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Viola Azizah Mahfudz', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Arif Hidayat Ramadhan', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Aura Hanifa Kasetya Putri', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Faizal Eka Setiawan', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Henny Merry Astutik', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Muhammad Muhlis Aditya Nur Wahid', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Nia Aulia', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Triangga Hafid Rifa\'i', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Zahira Priyan Husna', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Aris Kristiawan', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Avita Mumtahana', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Ferdian Hikmal Saputra', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Kaylla Zahrani', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Nabhan Athallah', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Nur Na\'imah Ma\'ruf', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Wisnu Budi Utomo', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Zhafira Sany Lailla Habibah', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Bramantyo Putra Rachmandani', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Diah Ayu Nur Rahmadani', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Ilham Tesa Nur Mazua', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Nadia Nur Nisrina', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Narangga Khoirul Utama', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Rizkyana Azka Akhiria Ramadhanti', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Alisha Islami Zukhruf', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Burhanudin Alfadlil Prastyo', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Fadzilla Kusuma Ningrum', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Muhammad Ludvi Argorahayu', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Nailis Sahila', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Naufal Dzaki Zaidan', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Sabila Bintang Kusuma Dewi', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Desty Ananda Putri', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Lucky Aprilia Dewi', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Muhammad Syarif Lutfi', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Annisa Rizqiya Hanum', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Chandra Halim Abdurrahman', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Devinta Sasta Azalia Putri', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Lusty Nafis Dwi Kartika', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Muhammad Vitto Siregar', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Valerina Najwa Khayla', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Aziz Hidayatulloh', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Azka Annisa Ramadhani', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Dafa Ibra Yuliawan', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Hasna Fathin Nur Diniyah', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Khilwa Layyina', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Muji Rahayu', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Naufal Gama Adikara', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Belinda Maulina Pujawargana', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Dinur Idhardinanta', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Indah Dwi Yuniati', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Nabila Aulia Hernina Mareta', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Satria Frahma Afrishal', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Aan Hidayat Tulloh', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Dea Febriana Azahra', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Ilyas Ramadhan', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Isnaini Putri Laili Nur Alimah', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Nadine Rolanda Cantika', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Alfa Yusuf Muhaimin', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Anindya Zahra Damayanti', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Deka Sholiha Kartika Habsari', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Karina Tri Handayani', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Muhamad Naufal Mazidan', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Raihanah Hanun Abidah', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Amalia Dwi Nurrahma', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Andika Prastya', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Della Rahmatika', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Lintang Pertiwi', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Muhammad Barkah Amaliansyah', 'jenis_kelamin' => 'Pria', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Rona Marsa', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Salma Hajidah', 'jenis_kelamin' => 'Wanita', 'himada' => 'JatengStis']);
        User::create(['nama' => 'Frendy Tigor Wiratama Sinaga', 'jenis_kelamin' => 'Pria', 'himada' => 'Saburai']);
        User::create(['nama' => 'Yerikho', 'jenis_kelamin' => 'Pria', 'himada' => 'Saburai']);
        User::create(['nama' => 'Athiyah Tsurayya', 'jenis_kelamin' => 'Wanita', 'himada' => 'Saburai']);
        User::create(['nama' => 'Andrian Fajar Fahmi', 'jenis_kelamin' => 'Pria', 'himada' => 'Saburai']);
        User::create(['nama' => 'Muhammad Raihan Amin', 'jenis_kelamin' => 'Pria', 'himada' => 'Saburai']);
        User::create(['nama' => 'Zidan Septian', 'jenis_kelamin' => 'Pria', 'himada' => 'Saburai']);
        User::create(['nama' => 'M.Naufal Khansa', 'jenis_kelamin' => 'Pria', 'himada' => 'Saburai']);
        User::create(['nama' => 'Marsya Audia Cholisah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Saburai']);
        User::create(['nama' => 'Muhammad Akmal Sabiq', 'jenis_kelamin' => 'Pria', 'himada' => 'Saburai']);
        User::create(['nama' => 'Nurul Izzah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Saburai']);
        User::create(['nama' => 'Muhammad Choiri Krisna Arsyad', 'jenis_kelamin' => 'Pria', 'himada' => 'Saburai']);
        User::create(['nama' => 'Rahma Donna Valencia Putri', 'jenis_kelamin' => 'Wanita', 'himada' => 'Saburai']);
        User::create(['nama' => 'Ade Irma', 'jenis_kelamin' => 'Wanita', 'himada' => 'Saburai']);
        User::create(['nama' => 'Putra Dafa Pratama', 'jenis_kelamin' => 'Pria', 'himada' => 'Saburai']);
        User::create(['nama' => 'Rulistia Amanda', 'jenis_kelamin' => 'Wanita', 'himada' => 'Saburai']);
        User::create(['nama' => 'Aura Mustika Febrina', 'jenis_kelamin' => 'Wanita', 'himada' => 'Saburai']);
        User::create(['nama' => 'Candra Alfareza', 'jenis_kelamin' => 'Pria', 'himada' => 'Saburai']);
        User::create(['nama' => 'Sabrina Nur Azizza', 'jenis_kelamin' => 'Wanita', 'himada' => 'Saburai']);
        User::create(['nama' => 'Dimas Rizki Azani', 'jenis_kelamin' => 'Pria', 'himada' => 'Saburai']);
        User::create(['nama' => 'Izqyfa Syafiq Ayasha', 'jenis_kelamin' => 'Wanita', 'himada' => 'Saburai']);
        User::create(['nama' => 'Galih Prastyawan', 'jenis_kelamin' => 'Pria', 'himada' => 'Saburai']);
        User::create(['nama' => 'Lya Karimatul Fitri', 'jenis_kelamin' => 'Wanita', 'himada' => 'Saburai']);
        User::create(['nama' => 'Arini Rahmah Kamila', 'jenis_kelamin' => 'Wanita', 'himada' => 'Rinjani']);
        User::create(['nama' => 'Baiq Nadiatul Ismi', 'jenis_kelamin' => 'Wanita', 'himada' => 'Rinjani']);
        User::create(['nama' => 'Kadek Argyanti', 'jenis_kelamin' => 'Wanita', 'himada' => 'Rinjani']);
        User::create(['nama' => 'Ilma Fitriatul \'Assri', 'jenis_kelamin' => 'Wanita', 'himada' => 'Rinjani']);
        User::create(['nama' => 'Nela Nur ‘Azizah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Rinjani']);
        User::create(['nama' => 'M. Fikri Khaikal', 'jenis_kelamin' => 'Pria', 'himada' => 'Rinjani']);
        User::create(['nama' => 'Ananda Natasya', 'jenis_kelamin' => 'Wanita', 'himada' => 'Rinjani']);
        User::create(['nama' => 'Baiq Rohmah Sany Azzahro', 'jenis_kelamin' => 'Wanita', 'himada' => 'Rinjani']);
        User::create(['nama' => 'Rahman Al Gifary', 'jenis_kelamin' => 'Pria', 'himada' => 'Rinjani']);
        User::create(['nama' => 'Yulia Dwi Utari', 'jenis_kelamin' => 'Wanita', 'himada' => 'Rinjani']);
        User::create(['nama' => 'Safira Inayah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Rinjani']);
        User::create(['nama' => 'Syifa Dwi Aulia Putri', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Rafli Hibriansyah Siregar', 'jenis_kelamin' => 'Pria', 'himada' => 'Mavias']);
        User::create(['nama' => 'Irish Shanty Kinsella Puteri', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Seto Haidar Yudhistira', 'jenis_kelamin' => 'Pria', 'himada' => 'Mavias']);
        User::create(['nama' => 'Cahya Rama Vinanza', 'jenis_kelamin' => 'Pria', 'himada' => 'Mavias']);
        User::create(['nama' => 'Navisa Rahmawati', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Taura Davin Santosa', 'jenis_kelamin' => 'Pria', 'himada' => 'Mavias']);
        User::create(['nama' => 'Faizul Hanif', 'jenis_kelamin' => 'Pria', 'himada' => 'Mavias']);
        User::create(['nama' => 'Xavier Yubin Raditio', 'jenis_kelamin' => 'Pria', 'himada' => 'Mavias']);
        User::create(['nama' => 'Abdul Hanif Al Fatah', 'jenis_kelamin' => 'Pria', 'himada' => 'Mavias']);
        User::create(['nama' => 'Faliza Maulidina Syarief', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Muhamad Zidan Kurnia Ahida', 'jenis_kelamin' => 'Pria', 'himada' => 'Mavias']);
        User::create(['nama' => 'Balqis Hasna Syauqiyah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Valent Olivia Sijabat', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Ellen Sinta Marito', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'I Komang Andhika Putra Erawan', 'jenis_kelamin' => 'Pria', 'himada' => 'Mavias']);
        User::create(['nama' => 'Dimas Satria Ardilla', 'jenis_kelamin' => 'Pria', 'himada' => 'Mavias']);
        User::create(['nama' => 'Muhamad Fadhlan Hendri', 'jenis_kelamin' => 'Pria', 'himada' => 'Mavias']);
        User::create(['nama' => 'Fictoria Putri Andini', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Avril Irene Hutauruk', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Maulidya Putri Agella', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Muhammad Lazuardi Said Ahimsa Bahasoan', 'jenis_kelamin' => 'Pria', 'himada' => 'Mavias']);
        User::create(['nama' => 'Shania Yasmin Annisa', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Yodha Aldo Sri Adinata', 'jenis_kelamin' => 'Pria', 'himada' => 'Mavias']);
        User::create(['nama' => 'Dinda Putri Nabila', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Putri Yuli Yanti', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Siti Nayya Nur Astian', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Sri Dwi Hartasih', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Ghina Amalia Hidayati', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Syifa Hana Salsabila Nadra Gustari', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mavias']);
        User::create(['nama' => 'Syadza Salsabila', 'jenis_kelamin' => 'Wanita', 'himada' => 'KS3']);
        User::create(['nama' => 'Maulidia Destariani', 'jenis_kelamin' => 'Wanita', 'himada' => 'KS3']);
        User::create(['nama' => 'Muhamad Naufal Syafiq', 'jenis_kelamin' => 'Pria', 'himada' => 'KS3']);
        User::create(['nama' => 'Yudha Putra Tiara', 'jenis_kelamin' => 'Pria', 'himada' => 'KS3']);
        User::create(['nama' => 'Aprillya', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Wulan Septiani', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Fatikha Nuraziza', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Rosyiana', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Alifia Deanita', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Wahyu Nugraha', 'jenis_kelamin' => 'Laki-laki', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Miftahul Husna', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Amir Syaifudin', 'jenis_kelamin' => 'Pria', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Rani Kusumawati', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'M Nabil Alif', 'jenis_kelamin' => 'Pria', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Benedicta Aurelia', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'M Rizqi Rohmadani', 'jenis_kelamin' => 'Pria', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Haya Fauzia Adzakia', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Nadhiatuz Zahra', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Nuraini Fauziah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Danis Hanif Darmawan', 'jenis_kelamin' => 'Pria', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Pitra Raditya Amanda', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Ikhwan Wahyu', 'jenis_kelamin' => 'Pria', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'M Adiyasa Ihsani', 'jenis_kelamin' => 'Pria', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Ummi Fatimah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kbmsy']);
        User::create(['nama' => 'Ardi Wirahman', 'jenis_kelamin' => 'Pria', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Auliandari', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Hafidz Mas\'udiana Hakim', 'jenis_kelamin' => 'Pria', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Maylani Puspita Sari', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Diva Dwi Cahyo', 'jenis_kelamin' => 'Pria', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Rifqi Muhadzib Ahdan', 'jenis_kelamin' => 'Pria', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Naila Hanifa', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Yudistira Aldiwijaya', 'jenis_kelamin' => 'Pria', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Syaira Hasya Desiani', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Muhammad Daffa Dekananda', 'jenis_kelamin' => 'Pria', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Dinda Putri Nur Wulandari', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kajaba']);
        User::create(['nama' => 'In\'amu Rahim', 'jenis_kelamin' => 'Pria', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Najwa Alya Fauziah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Regita Maulidya Hidayat', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Rifki Siboro', 'jenis_kelamin' => 'Pria', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Caesar Rama Fahrezi', 'jenis_kelamin' => 'Pria', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Friscilia Siallagan', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Zahra Tamara Allyana', 'jenis_kelamin' => 'Wanita', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Chandra Gustian', 'jenis_kelamin' => 'Pria', 'himada' => 'Kajaba']);
        User::create(['nama' => 'Khabira Yudismaredi', 'jenis_kelamin' => 'Pria', 'himada' => 'Imsak']);
        User::create(['nama' => 'Awang Aviat', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imsak']);
        User::create(['nama' => 'Kelpin Saputra', 'jenis_kelamin' => 'Pria', 'himada' => 'Imsak']);
        User::create(['nama' => 'Roland Yohanes Renteng', 'jenis_kelamin' => 'Pria', 'himada' => 'Imsak']);
        User::create(['nama' => 'Mario Hoki Wijaya Wangsa Nata', 'jenis_kelamin' => 'Pria', 'himada' => 'Imsak']);
        User::create(['nama' => 'Nur Hafizatun Nissa', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imsak']);
        User::create(['nama' => 'Muhammad Ridho Purwanto', 'jenis_kelamin' => 'Pria', 'himada' => 'Imsak']);
        User::create(['nama' => 'Muhammad Zain Al Azhari', 'jenis_kelamin' => 'Pria', 'himada' => 'Imsak']);
        User::create(['nama' => 'Fariz Ahmad Wijaksara', 'jenis_kelamin' => 'Pria', 'himada' => 'Imsak']);
        User::create(['nama' => 'Pranaja Rulif', 'jenis_kelamin' => 'Pria', 'himada' => 'Imsak']);
        User::create(['nama' => 'Husna Sabila Mujahidah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imsak']);
        User::create(['nama' => 'Muhammad Irfan', 'jenis_kelamin' => 'Pria', 'himada' => 'Imsak']);
        User::create(['nama' => 'Muhammad Naziel', 'jenis_kelamin' => 'Pria', 'himada' => 'Imsak']);
        User::create(['nama' => 'Tazkya Indira Putri', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imsak']);
        User::create(['nama' => 'Abetita Morais', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imf']);
        User::create(['nama' => 'Agustina beladewiana Madu', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imf']);
        User::create(['nama' => 'Altagracia Freitas Moniz', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imf']);
        User::create(['nama' => 'Christiano Teddy Anta', 'jenis_kelamin' => 'Pria', 'himada' => 'Imf']);
        User::create(['nama' => 'Dirce Justina Freitas Belo', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imf']);
        User::create(['nama' => 'Etelchia Sanches Guterres', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imf']);
        User::create(['nama' => 'Francisco Amaro Belo', 'jenis_kelamin' => 'Pria', 'himada' => 'Imf']);
        User::create(['nama' => 'Fridolin Claudio Ferreira Fernandes', 'jenis_kelamin' => 'Pria', 'himada' => 'Imf']);
        User::create(['nama' => 'Graziela Giana Nanini Alves Tilman', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imf']);
        User::create(['nama' => 'Marselina Beatrix Ngana', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imf']);
        User::create(['nama' => 'Meldiro A. F. Duarte da Cruz', 'jenis_kelamin' => 'Pria', 'himada' => 'Imf']);
        User::create(['nama' => 'Monica Li Piedade', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imf']);
        User::create(['nama' => 'Nelia Lopes', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imf']);
        User::create(['nama' => 'Sinezhia Siju De Araujo Andrade', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imf']);
        User::create(['nama' => 'Sancha Isabel Da Costa Xavier', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imf']);
        User::create(['nama' => 'Valentino Cristiadi Geong', 'jenis_kelamin' => 'Pria', 'himada' => 'Imf']);
        User::create(['nama' => 'Ricardo Soares De Jesus', 'jenis_kelamin' => 'Pria', 'himada' => 'Imf']);
        User::create(['nama' => 'Clarisse De Delgada Moreira Soares', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imf']);
        User::create(['nama' => 'Afifah Khairunnisa Piliang', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Ahmad Husein Nasution', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Amenli Ailsa Sitinjak', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Angelia Oktavia Br Tampubolon', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Arianto Barus', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Aurelia Dini Syafnadiva', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Carlos Armando Marganda Tua Sitohang', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Christi Jessica Halimah Siagian', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Christiano Yosaki', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'David Parasian Sihombing', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Dwi Novi Avtayana Putri Harahap', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Eby Gael Br Ginting', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Elsa Simbolon', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Febriansyah Muharram Rambe', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Ferdy Kusuma', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Florencia Feiga Putri Siregar', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Harry Pentaleon Rumahorbo', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Haykal Pasha Siregar', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Henry Kevin', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Ibrahim Bazra Ritonga', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Ignatius Raja Ondolan Naibaho', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Immanita Denawinta Ginting', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Immanuella Risna Sahalana Tumanggor', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Ingrid Vanessa Martina Samosir', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Joshua Naptali Hasian Siringo Ringo', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Juan Thomos Brian Siagian', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'July Natasya', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Kezia Dianrani Hutagalung', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Kurniawan Pratama Pasaribu', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Lady Theresia Simbolon', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Lichar Martaulina Sinaga', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Mario Mikail H. Simanjuntak', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Michael Klington Hutapea', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Moses Noel Estomihi Simanullang', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Muhammad Fakhri Habibi', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Muhyan Harahap', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Musada Sadana Wirja', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Nasywa Saniyyah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Nikita Anestasya Saragih', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Okhy Julianto Marbun', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Prisco Moses Candela Meliala', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'R. Razwa Fazila Wibowo', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Riani Br. Ginting', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Rido Gunawan Sitanggang', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Rizal Fakhruddin Nasution', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Rolando Hutabarat', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Santa Lusiana Simanjuntak', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Syafira Falatansya', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Tania Margaretha', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Tasya Amelia', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Teguh Christianto Simbolon', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Thoriq Aqil Sastra Lubis', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Twifanny Nadya Aprianti Sinaga', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Winona Ortina Tampubolon', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Yohana Herdianly Br Nainggolan', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassu']);
        User::create(['nama' => 'Zenas Samosir', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassu']);
        User::create(['nama' => 'Muhammad Rusydi Haryanto', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassi']);
        User::create(['nama' => 'Azzahra Widyatami', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Nalah Naurah Adyanto', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Rahmat Nuryadin', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassi']);
        User::create(['nama' => 'Ahmad Farhan', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassi']);
        User::create(['nama' => 'Aiskha Zahra Naislva', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Muhammad Syafiq Mambulu', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassi']);
        User::create(['nama' => 'Rezky Amaliah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Anggita Cristin Meylani', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'I.G.N. Ari Sadewa', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassi']);
        User::create(['nama' => 'Syadza Khumairah Akmul', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Ahmad Aikun', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassi']);
        User::create(['nama' => 'Aulia Ul Hasanah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Nailatur Rajaa', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Hanif Jawahir', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassi']);
        User::create(['nama' => 'Lisa Fajrianti', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Rezki Nur Amalia Haris', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Afifah Nur Ramadhani Zakiyah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Muhammad Aqsha Dewantoro', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassi']);
        User::create(['nama' => 'Yuliana', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Andi Muthiah Rahim', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Moh. Fajril Adiko', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassi']);
        User::create(['nama' => 'Muthia Hadi', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Rezky Aditya Ar\'razak', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassi']);
        User::create(['nama' => 'Andi Tenri Uleng', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Victor Ardiansyah Maruli Sitorus', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassi']);
        User::create(['nama' => 'Zahra Khairunnisa', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Annisa Ayu Sarita', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Anugrah Putri Indahsari Tria Meiliana', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Ardhiah Yayan Cahyani', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Sarah Nurfajar', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Ashy Sulfidah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Grace Queensha Dika', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Aura Mufthia Azzahra', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Hikmawati Ahmad', 'jenis_kelamin' => 'Wanita', 'himada' => 'Imassi']);
        User::create(['nama' => 'Muh Yusuf.S', 'jenis_kelamin' => 'Pria', 'himada' => 'Imassi']);
        User::create(['nama' => 'Abid Abiyyu Suwitra', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Agung Ismail', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Ahmad Adib Husaini AL Munawwar', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Danang Ivan Pangestu', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Efriyendi', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Fadhlurrahman Safli', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Fakhri Iqbar', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Farhiya Salsa Billa', 'jenis_kelamin' => 'Wanita', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Faruq Hadi Ramadhan', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Haris Farestu', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Juan Stevan Rehatta', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Karina Novrilia', 'jenis_kelamin' => 'Wanita', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Lidia Nisfi', 'jenis_kelamin' => 'Wanita', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Luthfia Nurul Izza', 'jenis_kelamin' => 'Wanita', 'himada' => 'Ikmm']);
        User::create(['nama' => 'M. Alfarizi Nul Hakim', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Marsya Mutia Maris', 'jenis_kelamin' => 'Wanita', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Muhammad Aulia Rahman', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Muhammad Habibi', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Muhammad Halim', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Muhammad Rafky Fernando', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Muhammad Rizaldi', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Raihan Taufiqurrahman Zaki', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Rifa Fairuz', 'jenis_kelamin' => 'Wanita', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Satria Imka Dwi Putra', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Syaiful Kabir', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Ultiva Ulandari', 'jenis_kelamin' => 'Wanita', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Waldy Abdurrahman', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Winni Elfira', 'jenis_kelamin' => 'Wanita', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Yoceylin Feby Sitorus', 'jenis_kelamin' => 'Wanita', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Yoga Prawira', 'jenis_kelamin' => 'Pria', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Zakia Faza Adila', 'jenis_kelamin' => 'Wanita', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Zuhroini Hayati', 'jenis_kelamin' => 'Wanita', 'himada' => 'Ikmm']);
        User::create(['nama' => 'Alifa Olganata', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himari']);
        User::create(['nama' => 'Laurensius Marsyal', 'jenis_kelamin' => 'Pria', 'himada' => 'Himari']);
        User::create(['nama' => 'Dhea Patikasari Napitupulu', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himari']);
        User::create(['nama' => 'Jessica La Ercadiola Br.Ginting', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himari']);
        User::create(['nama' => 'Ahmad Dzaky Dagna', 'jenis_kelamin' => 'Pria', 'himada' => 'Himari']);
        User::create(['nama' => 'Monic Angellica', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himari']);
        User::create(['nama' => 'Aurelia Ayala Naura', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himari']);
        User::create(['nama' => 'Evelyn Tan Eldisha Nawa', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himari']);
        User::create(['nama' => 'Muhammad Arkan Anzuye', 'jenis_kelamin' => 'Pria', 'himada' => 'Himari']);
        User::create(['nama' => 'Zaid Rizky Ziadi', 'jenis_kelamin' => 'Pria', 'himada' => 'Himari']);
        User::create(['nama' => 'Andini Oktariana Ningrum', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himari']);
        User::create(['nama' => 'Fais Jefli', 'jenis_kelamin' => 'Pria', 'himada' => 'Himari']);
        User::create(['nama' => 'Hanifa Armevia', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himari']);
        User::create(['nama' => 'Muhammad Faiz Alfatah', 'jenis_kelamin' => 'Pria', 'himada' => 'Himari']);
        User::create(['nama' => 'Imelda Elisabeth Manik', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himari']);
        User::create(['nama' => 'Josua Parasian Naibaho', 'jenis_kelamin' => 'Pria', 'himada' => 'Himari']);
        User::create(['nama' => 'Putri Helena', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himari']);
        User::create(['nama' => 'Syahlan Dwi Vizhta Mahendra', 'jenis_kelamin' => 'Pria', 'himada' => 'Himari']);
        User::create(['nama' => 'Ramuna Asnal', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himari']);
        User::create(['nama' => 'Roihan Febrian', 'jenis_kelamin' => 'Pria', 'himada' => 'Himari']);
        User::create(['nama' => 'Rut Sihotang', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himari']);
        User::create(['nama' => 'Syahirah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himari']);
        User::create(['nama' => 'Tiatira Eklesia Betah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himari']);
        User::create(['nama' => 'M. Satria', 'jenis_kelamin' => 'Pria', 'himada' => 'Himamira']);
        User::create(['nama' => 'Rizky Putra Pratama', 'jenis_kelamin' => 'Pria', 'himada' => 'Himamira']);
        User::create(['nama' => 'Viktor Fernando Manalu', 'jenis_kelamin' => 'Pria', 'himada' => 'Himamira']);
        User::create(['nama' => 'Padil Muhammad Zaki', 'jenis_kelamin' => 'Pria', 'himada' => 'Himamira']);
        User::create(['nama' => 'Rafifah Faradhilah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himamira']);
        User::create(['nama' => 'Josi Intan Tri RIzky', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himamira']);
        User::create(['nama' => 'Amanda Tri Hapsari', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himamira']);
        User::create(['nama' => 'Puspa Wulandari', 'jenis_kelamin' => 'Wanita', 'himada' => 'Himamira']);
        User::create(['nama' => 'Ahzuhra Najuwa', 'jenis_kelamin' => 'Wanita', 'himada' => 'Gist']);
        User::create(['nama' => 'M. Akbar Rinaldi', 'jenis_kelamin' => 'Pria', 'himada' => 'Gist']);
        User::create(['nama' => 'Muhammad Fouzan', 'jenis_kelamin' => 'Pria', 'himada' => 'Gist']);
        User::create(['nama' => 'Rahmat Ananda', 'jenis_kelamin' => 'Pria', 'himada' => 'Gist']);
        User::create(['nama' => 'Muhammad Hamlul Khair', 'jenis_kelamin' => 'Pria', 'himada' => 'Gist']);
        User::create(['nama' => 'Kessya Desyka Ayliyanda', 'jenis_kelamin' => 'Wanita', 'himada' => 'Gist']);
        User::create(['nama' => 'T.M. Al Asy\'ari Al-Muchtari', 'jenis_kelamin' => 'Pria', 'himada' => 'Gist']);
        User::create(['nama' => 'Andre Wari Gibson Simbolon', 'jenis_kelamin' => 'Pria', 'himada' => 'Gist']);
        User::create(['nama' => 'Fakhira Addia Mulawarman', 'jenis_kelamin' => 'Wanita', 'himada' => 'Gist']);
        User::create(['nama' => 'Lydia Aushaf Ozora Siregar', 'jenis_kelamin' => 'Wanita', 'himada' => 'Gist']);
        User::create(['nama' => 'Siti Hajar Fikraini', 'jenis_kelamin' => 'Wanita', 'himada' => 'Gist']);
        User::create(['nama' => 'Rahmat ML', 'jenis_kelamin' => 'Pria', 'himada' => 'Gist']);
        User::create(['nama' => 'Barra Ghita Pratiwi', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Nela Meriska Pratama', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Seftiana Laili Puji Lestari', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Febrian Justitiana', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Ratih Yuliana Putri', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Baran Hidayat Azzahra', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Hasna Nur Khoirunisa', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Resa Ferdhea Novita', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Syam Zulkarnain Fahim', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Annisa Raihana Mudzakir', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Farhan Kadhafi Azuansyah', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Hana Sabrina Fitria Abrora', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Mohammad Agam Bonanza', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Auliya Ahmada Ghinannafsa', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Galang Dwi Nugroho', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Ica Bali Tri Susmita', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Muhammad Haris Syah Putra', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Amalia Khoirum Mazidah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Amrestya Gaia Bujjhati Isbandi', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Cahyani Vevy Wandara', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Ilham Akbar Tauhid', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Johana Putri Natasya Sitorus', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Muhammad Imaddudin Zaki', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Anisa Giri Ramadhani', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Daffa Hibatullah R.T.P', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Difya Ayu Meisya Nurjanah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'M. Faruq Hafidzullah Erfaringga', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Qurany Nadhira Tsabita', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Sean Gusti Setyawan', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Fadhil Iqbal Murtadho', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Hening Piyasthi', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Nadila Ajeng Puspita Sari', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Hafero Nashru Prasetyo', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Innes Septian Amelia Putri', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Nadya Saphira Azzahra', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Praditya Rozaq Hartawan', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Andhin Intannegara', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Hafidh Dzaky Ats Tsaqif', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Ramadhani Zaki Suruuri', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Silvia Febrianti', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Davila Caramoy', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Helmi Handi Pratama', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Mervina Aulia Aisah', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Rayhan Ardi Fardian', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Yuli Fatmawati', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Adrian Januartha', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Denia Dwi Rosdiana', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Mirna Putri Firgiani', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Mohammad Zidane Akbar Satriaji', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Muhammad Nathan Bhamakerti Fazza', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Rizqi Arby Maulana', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Yulia Dwi Wahyuni', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Andra Adiputra Rudianto', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Fadiya Aisyah Nuraini', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Muchlis Nur Cahya', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Nabela Syafa Febriyanti', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Anggi Ferdian Sanly', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Frestia Fatikhatul Quro\'', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Muhammad Johan Firmansyah', 'jenis_kelamin' => 'Pria', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Nabila Putri Maulidiya', 'jenis_kelamin' => 'Wanita', 'himada' => 'Bekisar']);
        User::create(['nama' => 'Amanda Atika Putri', 'jenis_kelamin' => 'Wanita', 'himada' => 'Sms']);
        User::create(['nama' => 'Fero Alghirafi Akbar', 'jenis_kelamin' => 'Pria', 'himada' => 'Sms']);
        User::create(['nama' => 'Intan Pratiwi', 'jenis_kelamin' => 'Wanita', 'himada' => 'Sms']);
        User::create(['nama' => 'M. Alparizi', 'jenis_kelamin' => 'Pria', 'himada' => 'Sms']);
        User::create(['nama' => 'Maulida Mutiriani', 'jenis_kelamin' => 'Wanita', 'himada' => 'Sms']);
        User::create(['nama' => 'Nyimas Inayah Ayu Puari', 'jenis_kelamin' => 'Wanita', 'himada' => 'Sms']);
        User::create(['nama' => 'Nyimas Virna Salsa Lestari R.', 'jenis_kelamin' => 'Wanita', 'himada' => 'Sms']);
        User::create(['nama' => 'Mercy Febriella Liborang', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mpc']);
        User::create(['nama' => 'M. Rezky Raya Kilwouw', 'jenis_kelamin' => 'Pria', 'himada' => 'Mpc']);
        User::create(['nama' => 'Valentina Lasma Situmorang', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mpc']);
        User::create(['nama' => 'Decapryo Rivian Belo', 'jenis_kelamin' => 'Pria', 'himada' => 'Mpc']);
        User::create(['nama' => 'Sulastri Indira Putri Hamid', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mpc']);
        User::create(['nama' => 'Agnes Meliana Napitupulu', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mpc']);
        User::create(['nama' => 'Miranti Nabila Ramadhani', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mpc']);
        User::create(['nama' => 'Priskila Tesalonika Sihombing Nababan', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mpc']);
        User::create(['nama' => 'Oktovia Frinny Irianti Marimar Ivonne Leihitu', 'jenis_kelamin' => 'Wanita', 'himada' => 'Mpc']);
        User::create(['nama' => 'Ni Putu Christina Maharani Nada', 'jenis_kelamin' => 'Wanita', 'himada' => 'Balistis']);
        User::create(['nama' => 'I Wayan Ananda Murtika Wibawa', 'jenis_kelamin' => 'Pria', 'himada' => 'Balistis']);
        User::create(['nama' => 'Putu Ayudhia Pratami Putri', 'jenis_kelamin' => 'Wanita', 'himada' => 'Balistis']);
        User::create(['nama' => 'I Gede Rizky Putra Arnawa', 'jenis_kelamin' => 'Pria', 'himada' => 'Balistis']);
        User::create(['nama' => 'Luh Nyoman Ratih Swandewi Putri', 'jenis_kelamin' => 'Wanita', 'himada' => 'Balistis']);
        User::create(['nama' => 'Kadek Sri Nagitha Suaryanti', 'jenis_kelamin' => 'Wanita', 'himada' => 'Balistis']);
        User::create(['nama' => 'Ni Putu Karistya Paicha Maesi', 'jenis_kelamin' => 'Wanita', 'himada' => 'Balistis']);
        User::create(['nama' => 'Putu Sinta Pramastini', 'jenis_kelamin' => 'Wanita', 'himada' => 'Balistis']);
        User::create(['nama' => 'Gusti Ayu Made Putria Pebriani Dharmawan', 'jenis_kelamin' => 'Wanita', 'himada' => 'Balistis']);

    }
}

